tasks:
  scanning:
    steps:
    - checkout
    - commands:
      - |
          curl -L "$(curl -s https://api.github.com/repos/tenable/terrascan/releases/latest | grep -o -E "https://.+?_Darwin_x86_64.tar.gz")" > terrascan.tar.gz
          tar -xf terrascan.tar.gz terrascan && rm terrascan.tar.gz
          sudo install terrascan /usr/local/bin && rm terrascan
          cd terraform/aws

          terrascan scan -o junit-xml -x json > junit_report.xml 
          # sed -i '/{"/d' junit_report.xml
          # cat junit_report.xml
    - reports/junit:
        paths: ["junit_report.xml"] 


