global:
  runner:
    containers:
    - image: saurabh3460/terrascan:latest

tasks:
  scanning:
    steps:
    - checkout
    - commands:
      - |
          cd terraform/aws/
          terraform init
          cd ../../
          terrascan scan -o junit-xml -x json > junit_report.xml || true
          sed -i '/{"/d' junit_report.xml
          cat junit_report.xml
    - reports/junit:
        paths: ["junit_report.xml"]


